INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL_CODE, STREET)
VALUES (10001, 'Nairobi', 'Kenya', '1221', 'Kaunda Street');

INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL_CODE, STREET)
VALUES (10002, 'Mombasa', 'Kenya', '2222', 'Mtwapa Street');

INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL_CODE, STREET)
VALUES (10003, 'Meru', 'Kenya', '43433', 'Mwere Street');