INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL_CODE, STREET, CREATED_AT, UPDATED_AT)
VALUES (10001, 'Nairobi', 'Kenya', '1221', 'Kaunda Street', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL_CODE, STREET, CREATED_AT, UPDATED_AT)
VALUES (10002, 'Mombasa', 'Kenya', '2222', 'Mtwapa Street', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO ADDRESS (ID, CITY, COUNTRY, POSTAL_CODE, STREET, CREATED_AT, UPDATED_AT)
VALUES (10003, 'Meru', 'Kenya', '43433', 'Mwere Street', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- insert company type details --
INSERT INTO COMPANY_TYPE  (ID, NAME, CREATED_AT, UPDATED_AT)
VALUES (10003, 'Brewery', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());